#%RAML 1.0
title: Database Sharding
description: Proof of concept - Database Sharding
mediaType: application/json

/{id}:
  get:
    description: Get a person based on its ID.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "person": {
                    "id": "200",
                    "name": "Serrano, Bradford"
                },
                "db": "5433"
              }
      400:
        body:
          application/json - Example - Person not found:
            example: |
              {"error": "Person not found"}